title: "Malware Analysis Blog"
description: "Reverse-engineering and malware analysis write-ups"
url: "https://reh7061.github.io"
baseurl: "" # root
repository: reh7061/malware-blog
remote_theme: "mmistakes/minimal-mistakes@4.27.1"

# Skin can be overridden in custom CSS; keep dark-friendly default
minimal_mistakes_skin: "dark"
locale: "en-US"

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      author_profile: false
      toc           : true
      toc_sticky: true
      layout: single

paginate: 5 # amount of posts to show
paginate_path: /posts:num/
plugins:
  - jekyll-paginate-v2